version: '3.9'

services:
  freqtrade:
    image: freqtradeorg/freqtrade:develop
    container_name: sentinel_core
    restart: unless-stopped
    volumes:
      - ./freqtrade/user_data:/freqtrade/user_data
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy AdvancedVolatilityBreakout